[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../../../../ballerina/lib/javax.mail-1.6.2.jar"

[[platform.java11.dependency]]
path = "../../../../test-utils/build/libs/email-test-utils-2.2.1-SNAPSHOT.jar"
