---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "jmeter"
  name: "client-svc"
spec:
  ports:
    - name: "client-port"
      port: 3025
      protocol: "TCP"
      targetPort: 3025
  selector:
    app: "jmeter"
  type: "ClusterIP"
