[package]
org = "ballerina"
name = "email"
version = "2.0.1"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "./lib/javax.mail-1.6.2.jar"

[[platform.java11.dependency]]
path = "./lib/greenmail-1.5.11.jar"

[[platform.java11.dependency]]
path = "./lib/mimepull-1.9.11.jar"

[[platform.java11.dependency]]
path = "./lib/testng-7.4.0.jar"

[[platform.java11.dependency]]
path = "../native/build/libs/email-native-2.0.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/email-test-utils-2.0.1-SNAPSHOT.jar"
scope = "testOnly"
